<a href="https://colab.research.google.com/github/shubham570/Machine_learning/blob/master/Prob2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
c=np.arange(100,200,5)
c

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [8]:
d=c[0:16]
d

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175])

In [9]:
e=d.reshape(8,2)
e

array([[100, 105],
       [110, 115],
       [120, 125],
       [130, 135],
       [140, 145],
       [150, 155],
       [160, 165],
       [170, 175]])